### ISSUE TITLE
（老哥没错又是我）Windows10 命令行运行HupuApp的bug

### ISSUE THREAD

**Issue by Harmonicahappy** [wudizhangzhi/HupuApp#3]
* 操作系统：Windows10家庭普通版
* Python版本：2.7.13（通过Anaconda2安装）

Windows10下已经成功安装：
```python
Collecting HupuApp
Requirement already satisfied: six>=1.10.0 in h:\anaconda2\lib\site-packages (from HupuApp)
Requirement already satisfied: websocket-client==0.46.0 in h:\anaconda2\lib\site-packages (from HupuApp)
Requirement already satisfied: user-agent==0.1.9 in h:\anaconda2\lib\site-packages (from HupuApp)
Requirement already satisfied: colored==1.3.5 in h:\anaconda2\lib\site-packages (from HupuApp)
Requirement already satisfied: future==0.16.0 in h:\anaconda2\lib\site-packages (from HupuApp)
Requirement already satisfied: docopt==0.6.2 in h:\anaconda2\lib\site-packages (from HupuApp)
Requirement already satisfied: requests==2.18.4 in h:\anaconda2\lib\site-packages (from HupuApp)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in h:\anaconda2\lib\site-packages (from requests==2.18.4->HupuApp)
Requirement already satisfied: idna<2.7,>=2.5 in h:\anaconda2\lib\site-packages (from requests==2.18.4->HupuApp)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in h:\anaconda2\lib\site-packages (from requests==2.18.4->HupuApp)
Requirement already satisfied: certifi>=2017.4.17 in h:\anaconda2\lib\site-packages (from requests==2.18.4->HupuApp)
Installing collected packages: HupuApp
Successfully installed HupuApp-1.0.9
```
但是命令行运行`HupuApp`时出现如下错误：
```python
Traceback (most recent call last):
  File "h:\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "h:\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "H:\Anaconda2\Scripts\HupuApp.exe\__main__.py", line 5, in <module>
  File "h:\anaconda2\lib\site-packages\hupu\hupuapp.py", line 31, in <module>
    import curses
  File "h:\anaconda2\lib\curses\__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
```
## 原因及解决办法：
Windows不支持`curses`，所以得去https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses 下载符合系统版本的whl，然后命令行使用 `python -m pip install xxx.whl`，安装了以后才能在Windows下运行HupuApp

**Comment by wudizhangzhi** [comment]
@Harmonicahappy 多谢！

**Comment by Allianzcortex** [comment]
代码和注释写的都挺好的哇 有些人回复的太扯了
